# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170221_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='topics',
            field=models.ManyToManyField(to='api.Topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(to='api.Topic'),
        ),
    ]
