# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170221_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Community'),
            preserve_default=False,
        ),
    ]
