# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_community_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(to='api.Community'),
        ),
    ]
