# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Discussion',
        ),
    ]
