# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170222_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.URLField(default='http://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2014/05/01/101633169-483441581.530x298.jpg'),
            preserve_default=False,
        ),
    ]
